// <auto-generated />
using System;
using ExaminationSystem.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExaminationSystem.Persistence.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260417024955_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.UseTptMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "A1B2C3D4-E5F6-7890-ABCD-EF1234567890",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Email = "admin@system.com",
                            EmailConfirmed = true,
                            FailedLoginAttempts = 0,
                            FullName = "System Administrator",
                            IsDeleted = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@SYSTEM.COM",
                            NormalizedUserName = "ADMIN@SYSTEM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ5tQaHbHsOFCiMfQHvFAAFcQUQxkMECnxU2TlxRFiHjlRl3T5UdqKQqTuJdxZw2dA==",
                            PhoneNumberConfirmed = false,
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            SecurityStamp = "A1B2C3D4E5F6789012345678901234AB",
                            Status = (byte)0,
                            TwoFactorEnabled = false,
                            UserName = "admin@system.com"
                        });
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.AttemptAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SelectedOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelectedOptionId");

                    b.ToTable("AttemptAnswers", (string)null);
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.AttemptResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Passed")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionBreakdownJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId")
                        .IsUnique();

                    b.ToTable("AttemptResults", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1f2a3b4-c5d6-7891-efa1-901234567891"),
                            AttemptId = new Guid("f6a7b8c9-d0e1-2345-fabc-456789012345"),
                            CalculatedAt = new DateTime(2026, 2, 1, 10, 25, 30, 0, DateTimeKind.Utc),
                            CorrectCount = 2,
                            CreatedAt = new DateTime(2026, 2, 1, 10, 25, 30, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Passed = true,
                            QuestionBreakdownJson = "[]",
                            Score = 66.67m,
                            TotalQuestions = 3
                        });
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.Diploma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("QuizCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Diplomas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2d21ae7d-d8a0-4f19-9509-f39b5b339a7f"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "A foundational backend program covering architecture, APIs, and persistence.",
                            Duration = 24,
                            IsDeleted = false,
                            QuizCount = 1,
                            Status = 1,
                            Title = "Backend Engineering Diploma"
                        },
                        new
                        {
                            Id = new Guid("8480d832-e7da-4f56-9a58-91d90a51e683"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "A practical cloud engineering track with CI/CD, IaC, and monitoring.",
                            Duration = 20,
                            IsDeleted = false,
                            QuizCount = 1,
                            Status = 0,
                            Title = "Cloud & DevOps Diploma"
                        });
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DiplomaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DiplomaId");

                    b.HasIndex("UserId");

                    b.ToTable("Enrollments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-defa-234567890123"),
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            DiplomaId = new Guid("2d21ae7d-d8a0-4f19-9509-f39b5b339a7f"),
                            EnrolledAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Status = (byte)0,
                            UserId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-1234-efab-345678901234"),
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            DiplomaId = new Guid("8480d832-e7da-4f56-9a58-91d90a51e683"),
                            EnrolledAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Status = (byte)0,
                            UserId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012")
                        });
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.LoginLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoginLogs", (string)null);
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.OtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<byte>("Purpose")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OtpCodes", (string)null);
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Explanation")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1f2a3b4-c5d6-7890-efa1-901234567890"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Explanation = "PUT is idempotent — calling it multiple times produces the same result.",
                            IsDeleted = false,
                            OrderIndex = 1,
                            QuizId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Text = "Which HTTP method is idempotent and should be used to fully replace a resource?",
                            Type = (byte)2
                        },
                        new
                        {
                            Id = new Guid("f2a3b4c5-d6e7-8901-fab2-012345678901"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Explanation = "D stands for Dependency Inversion — high-level modules should not depend on low-level modules.",
                            IsDeleted = false,
                            OrderIndex = 2,
                            QuizId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Text = "What does the SOLID principle 'D' stand for?",
                            Type = (byte)2
                        },
                        new
                        {
                            Id = new Guid("a3b4c5d6-e7f8-9012-abc3-123456789012"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Explanation = "Statelessness and uniform interface are both core REST constraints defined by Fielding.",
                            IsDeleted = false,
                            OrderIndex = 3,
                            QuizId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Text = "Which of the following are valid REST constraints?",
                            Type = (byte)0
                        },
                        new
                        {
                            Id = new Guid("b4c5d6e7-f8a9-0123-bcd4-234567890123"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Explanation = "A liveness probe tells Kubernetes whether to restart a container.",
                            IsDeleted = false,
                            OrderIndex = 1,
                            QuizId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Text = "What is the primary purpose of a Kubernetes liveness probe?",
                            Type = (byte)2
                        },
                        new
                        {
                            Id = new Guid("c5d6e7f8-a9b0-1234-cde5-345678901234"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Explanation = "Terraform by HashiCorp uses HCL and supports multiple cloud providers.",
                            IsDeleted = false,
                            OrderIndex = 2,
                            QuizId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Text = "Which IaC tool uses a declarative HCL syntax and is cloud-agnostic?",
                            Type = (byte)2
                        },
                        new
                        {
                            Id = new Guid("d6e7f8a9-b0c1-2345-def6-456789012345"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Explanation = "Kubernetes and Docker Swarm are both container orchestration platforms.",
                            IsDeleted = false,
                            OrderIndex = 3,
                            QuizId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Text = "Which of the following are container orchestration platforms?",
                            Type = (byte)0
                        });
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9b0c1d2-e3f4-5678-abc9-789012345678"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsCorrect = true,
                            IsDeleted = false,
                            OrderIndex = 1,
                            QuestionId = new Guid("e1f2a3b4-c5d6-7890-efa1-901234567890"),
                            Text = "PUT"
                        },
                        new
                        {
                            Id = new Guid("a9b0c1d2-e3f4-5678-abc9-789012345679"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsCorrect = false,
                            IsDeleted = false,
                            OrderIndex = 2,
                            QuestionId = new Guid("e1f2a3b4-c5d6-7890-efa1-901234567890"),
                            Text = "POST"
                        },
                        new
                        {
                            Id = new Guid("a9b0c1d2-e3f4-5678-abc9-78901234567a"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsCorrect = false,
                            IsDeleted = false,
                            OrderIndex = 3,
                            QuestionId = new Guid("e1f2a3b4-c5d6-7890-efa1-901234567890"),
                            Text = "PATCH"
                        },
                        new
                        {
                            Id = new Guid("a9b0c1d2-e3f4-5678-abc9-78901234567b"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsCorrect = false,
                            IsDeleted = false,
                            OrderIndex = 4,
                            QuestionId = new Guid("e1f2a3b4-c5d6-7890-efa1-901234567890"),
                            Text = "DELETE"
                        },
                        new
                        {
                            Id = new Guid("d2e3f4a5-b6c7-8901-def2-012345678902"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsCorrect = true,
                            IsDeleted = false,
                            OrderIndex = 1,
                            QuestionId = new Guid("f2a3b4c5-d6e7-8901-fab2-012345678901"),
                            Text = "Dependency Inversion"
                        },
                        new
                        {
                            Id = new Guid("d2e3f4a5-b6c7-8901-def2-012345678903"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsCorrect = false,
                            IsDeleted = false,
                            OrderIndex = 2,
                            QuestionId = new Guid("f2a3b4c5-d6e7-8901-fab2-012345678901"),
                            Text = "Data Driven"
                        },
                        new
                        {
                            Id = new Guid("d2e3f4a5-b6c7-8901-def2-012345678904"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsCorrect = false,
                            IsDeleted = false,
                            OrderIndex = 3,
                            QuestionId = new Guid("f2a3b4c5-d6e7-8901-fab2-012345678901"),
                            Text = "Domain Driven"
                        },
                        new
                        {
                            Id = new Guid("d2e3f4a5-b6c7-8901-def2-012345678905"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsCorrect = false,
                            IsDeleted = false,
                            OrderIndex = 4,
                            QuestionId = new Guid("f2a3b4c5-d6e7-8901-fab2-012345678901"),
                            Text = "Decorator Pattern"
                        },
                        new
                        {
                            Id = new Guid("a5b6c7d8-e9f0-1234-abc5-345678901235"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsCorrect = true,
                            IsDeleted = false,
                            OrderIndex = 1,
                            QuestionId = new Guid("a3b4c5d6-e7f8-9012-abc3-123456789012"),
                            Text = "Statelessness"
                        },
                        new
                        {
                            Id = new Guid("a5b6c7d8-e9f0-1234-abc5-345678901236"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsCorrect = false,
                            IsDeleted = false,
                            OrderIndex = 2,
                            QuestionId = new Guid("a3b4c5d6-e7f8-9012-abc3-123456789012"),
                            Text = "Persistent sessions"
                        },
                        new
                        {
                            Id = new Guid("a5b6c7d8-e9f0-1234-abc5-345678901237"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsCorrect = false,
                            IsDeleted = false,
                            OrderIndex = 3,
                            QuestionId = new Guid("a3b4c5d6-e7f8-9012-abc3-123456789012"),
                            Text = "Server-side rendering"
                        },
                        new
                        {
                            Id = new Guid("a5b6c7d8-e9f0-1234-abc5-345678901238"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsCorrect = false,
                            IsDeleted = false,
                            OrderIndex = 4,
                            QuestionId = new Guid("a3b4c5d6-e7f8-9012-abc3-123456789012"),
                            Text = "Tight coupling"
                        },
                        new
                        {
                            Id = new Guid("b4c5d6e7-f8a9-0124-bcd4-234567890124"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsCorrect = true,
                            IsDeleted = false,
                            OrderIndex = 1,
                            QuestionId = new Guid("b4c5d6e7-f8a9-0123-bcd4-234567890123"),
                            Text = "Tells Kubernetes whether to restart a container"
                        },
                        new
                        {
                            Id = new Guid("b4c5d6e7-f8a9-0124-bcd4-234567890125"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsCorrect = false,
                            IsDeleted = false,
                            OrderIndex = 2,
                            QuestionId = new Guid("b4c5d6e7-f8a9-0123-bcd4-234567890123"),
                            Text = "Measures CPU usage"
                        },
                        new
                        {
                            Id = new Guid("b4c5d6e7-f8a9-0124-bcd4-234567890126"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsCorrect = false,
                            IsDeleted = false,
                            OrderIndex = 3,
                            QuestionId = new Guid("b4c5d6e7-f8a9-0123-bcd4-234567890123"),
                            Text = "Configures ingress routing"
                        },
                        new
                        {
                            Id = new Guid("b4c5d6e7-f8a9-0124-bcd4-234567890127"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsCorrect = false,
                            IsDeleted = false,
                            OrderIndex = 4,
                            QuestionId = new Guid("b4c5d6e7-f8a9-0123-bcd4-234567890123"),
                            Text = "Authenticates users"
                        },
                        new
                        {
                            Id = new Guid("c5d6e7f8-a9b0-1235-cde5-345678901235"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsCorrect = true,
                            IsDeleted = false,
                            OrderIndex = 1,
                            QuestionId = new Guid("c5d6e7f8-a9b0-1234-cde5-345678901234"),
                            Text = "Terraform"
                        },
                        new
                        {
                            Id = new Guid("c5d6e7f8-a9b0-1235-cde5-345678901236"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsCorrect = false,
                            IsDeleted = false,
                            OrderIndex = 2,
                            QuestionId = new Guid("c5d6e7f8-a9b0-1234-cde5-345678901234"),
                            Text = "Ansible"
                        },
                        new
                        {
                            Id = new Guid("c5d6e7f8-a9b0-1235-cde5-345678901237"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsCorrect = false,
                            IsDeleted = false,
                            OrderIndex = 3,
                            QuestionId = new Guid("c5d6e7f8-a9b0-1234-cde5-345678901234"),
                            Text = "CloudFormation"
                        },
                        new
                        {
                            Id = new Guid("c5d6e7f8-a9b0-1235-cde5-345678901238"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsCorrect = false,
                            IsDeleted = false,
                            OrderIndex = 4,
                            QuestionId = new Guid("c5d6e7f8-a9b0-1234-cde5-345678901234"),
                            Text = "Puppet"
                        },
                        new
                        {
                            Id = new Guid("d6e7f8a9-b0c1-2346-def6-456789012346"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsCorrect = true,
                            IsDeleted = false,
                            OrderIndex = 1,
                            QuestionId = new Guid("d6e7f8a9-b0c1-2345-def6-456789012345"),
                            Text = "Kubernetes"
                        },
                        new
                        {
                            Id = new Guid("d6e7f8a9-b0c1-2346-def6-456789012347"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsCorrect = false,
                            IsDeleted = false,
                            OrderIndex = 2,
                            QuestionId = new Guid("d6e7f8a9-b0c1-2345-def6-456789012345"),
                            Text = "Git"
                        },
                        new
                        {
                            Id = new Guid("d6e7f8a9-b0c1-2346-def6-456789012348"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsCorrect = false,
                            IsDeleted = false,
                            OrderIndex = 3,
                            QuestionId = new Guid("d6e7f8a9-b0c1-2345-def6-456789012345"),
                            Text = "Jenkins"
                        },
                        new
                        {
                            Id = new Guid("d6e7f8a9-b0c1-2346-def6-456789012349"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsCorrect = false,
                            IsDeleted = false,
                            OrderIndex = 4,
                            QuestionId = new Guid("d6e7f8a9-b0c1-2345-def6-456789012345"),
                            Text = "Nginx"
                        });
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DiplomaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<int>("PassScore")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("DiplomaId");

                    b.ToTable("Quizzes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            DiplomaId = new Guid("2d21ae7d-d8a0-4f19-9509-f39b5b339a7f"),
                            DurationMinutes = 30,
                            Instructions = "Answer all questions within the time limit.",
                            IsDeleted = false,
                            MaxAttempts = 3,
                            PassScore = 60,
                            Status = (byte)1,
                            Title = "C# Fundamentals Quiz"
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            DiplomaId = new Guid("8480d832-e7da-4f56-9a58-91d90a51e683"),
                            DurationMinutes = 20,
                            Instructions = "Choose the best answer for each question.",
                            IsDeleted = false,
                            MaxAttempts = 5,
                            PassScore = 70,
                            Status = (byte)0,
                            Title = "Docker Basics Quiz"
                        });
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.QuizAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("UserId");

                    b.ToTable("QuizAttempts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-2345-fabc-456789012345"),
                            CreatedAt = new DateTime(2026, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Deadline = new DateTime(2026, 2, 1, 10, 30, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            QuizId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            StartTime = new DateTime(2026, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = (byte)2,
                            SubmittedAt = new DateTime(2026, 2, 1, 10, 25, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012")
                        },
                        new
                        {
                            Id = new Guid("a7b8c9d0-e1f2-3456-abcd-567890123456"),
                            CreatedAt = new DateTime(2026, 2, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Deadline = new DateTime(2026, 2, 10, 9, 20, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            QuizId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            StartTime = new DateTime(2026, 2, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = (byte)1,
                            UserId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012")
                        },
                        new
                        {
                            Id = new Guid("b8c9d0e1-f2a3-4567-bcde-678901234567"),
                            CreatedAt = new DateTime(2027, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Deadline = new DateTime(2027, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            QuizId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            StartTime = new DateTime(2027, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = (byte)1,
                            UserId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012")
                        });
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.Student", b =>
                {
                    b.HasBaseType("ExaminationSystem.Domain.Entities.AppUser");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C3D4E5F6-A7B8-9012-CDEF-123456789012",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Email = "student@system.com",
                            EmailConfirmed = true,
                            FailedLoginAttempts = 0,
                            FullName = "Default Student",
                            IsDeleted = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "STUDENT@SYSTEM.COM",
                            NormalizedUserName = "STUDENT@SYSTEM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEK5GJ3Nk8bHfRqM2p7vYWT+9GrwHZk8ZHMHw3pO4c9E2pOqOUM3uLgIrS7lQx6xB==",
                            PhoneNumberConfirmed = false,
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            SecurityStamp = "C3D4E5F6A7B890123456789012345CDE",
                            Status = (byte)0,
                            TwoFactorEnabled = false,
                            UserName = "student@system.com"
                        });
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.AttemptAnswer", b =>
                {
                    b.HasOne("ExaminationSystem.Domain.Entities.QuizAttempt", "Attempt")
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExaminationSystem.Domain.Entities.Question", "Question")
                        .WithMany("AttemptAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExaminationSystem.Domain.Entities.QuestionOption", "SelectedOption")
                        .WithMany("AttemptAnswers")
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attempt");

                    b.Navigation("Question");

                    b.Navigation("SelectedOption");
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.AttemptResult", b =>
                {
                    b.HasOne("ExaminationSystem.Domain.Entities.QuizAttempt", "Attempt")
                        .WithOne("Result")
                        .HasForeignKey("ExaminationSystem.Domain.Entities.AttemptResult", "AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attempt");
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("ExaminationSystem.Domain.Entities.Diploma", "Diploma")
                        .WithMany("Enrollments")
                        .HasForeignKey("DiplomaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExaminationSystem.Domain.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Diploma");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.LoginLog", b =>
                {
                    b.HasOne("ExaminationSystem.Domain.Entities.AppUser", "User")
                        .WithMany("LoginLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.OtpCode", b =>
                {
                    b.HasOne("ExaminationSystem.Domain.Entities.AppUser", "User")
                        .WithMany("OtpCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("ExaminationSystem.Domain.Entities.AppUser", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.Question", b =>
                {
                    b.HasOne("ExaminationSystem.Domain.Entities.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.QuestionOption", b =>
                {
                    b.HasOne("ExaminationSystem.Domain.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.Quiz", b =>
                {
                    b.HasOne("ExaminationSystem.Domain.Entities.Diploma", "Diploma")
                        .WithMany("Quizzes")
                        .HasForeignKey("DiplomaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diploma");
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.QuizAttempt", b =>
                {
                    b.HasOne("ExaminationSystem.Domain.Entities.Quiz", "Quiz")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExaminationSystem.Domain.Entities.Student", "Student")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ExaminationSystem.Domain.Entities.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ExaminationSystem.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ExaminationSystem.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExaminationSystem.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ExaminationSystem.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.Student", b =>
                {
                    b.HasOne("ExaminationSystem.Domain.Entities.AppUser", null)
                        .WithOne()
                        .HasForeignKey("ExaminationSystem.Domain.Entities.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("LoginLogs");

                    b.Navigation("OtpCodes");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.Diploma", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.Question", b =>
                {
                    b.Navigation("AttemptAnswers");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.QuestionOption", b =>
                {
                    b.Navigation("AttemptAnswers");
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.Quiz", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("QuizAttempts");
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.QuizAttempt", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("ExaminationSystem.Domain.Entities.Student", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("QuizAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
